<?php

/**
 * Convert a string to a slug, safe for use in urls
 * @param string
 * @return string
 */
function alogo_to_slug($string){
	$string = str_replace(array('/', ' ', '&'), '-', $string);
  $accents = '/&([A-Za-z]{1,2})(tilde|grave|acute|circ|cedil|uml|lig);/';
  return urlencode(strtolower(preg_replace($accents, '$1', htmlentities(utf8_decode($string)))));
}

/**
 * Valida um CPF
 * @param string
 * @return bool
 */
function alogo_validate_cpf($cpf) {
  $regex = '/^[0-9]{3}(.)?[0-9]{3}(.)?[0-9]{3}(-)?[0-9]{2}$/';
  return (bool) preg_match($regex, $cpf);
}

/**
 * Valida um Email
 * @param string
 * @return bool
 */
function alogo_validate_email($email) {
  $regex = "/^[a-z0-9]+[a-z0-9\?\.\+-_]*"."@[a-z0-9_-]+(\.[a-z0-9_-]+)*\.[a-z]+$/";
  return (bool) preg_match($regex, $email);
}

/**
 * Implementation of hook_cron().
 */
function alogo_utils_cron() {
  $resource = db_query("SHOW tables");
  $tables = array();
  
  while($row = db_fetch_array($resource)) {
    $tables[] = current($row);
  }
  
  $query = 'OPTIMIZE TABLE ' . implode(', ', $tables);
  $result = db_query($query);
  
  if($result === false) {
    watchdog('alogo_utils', 'Error Optimizing Database, query: %query', array('%query' => $query), WATCHDOG_ERROR);
  }else{
    watchdog('alogo_utils', 'Optimized Database');
  }
}
