<?php
/**
 * @file Alogo PNG Drupal Hooks
 */

/**
 * Implements hook_help().
 */
function alogo_png_help($path = '', $arg = NULL) {
  $output = '';
  switch ($path) {
    case 'admin/help#alogo_png':
    case 'admin/settings/alogo_png':
      $output = '<p>'. t('Unlike other PNG fix scripts for IE6, DD_belatedpng ensure that background-position and background-repeat are properly supported and fixes the grey background issue.'). '</p>
			<p>'.t('There is no usage of AlphaImageLoader, so script doesn\'t have the buggy z-indexing associated with that filter.').'</p><p>DD_belatedpng was made by <a href="http://www.dillerdesign.com/experiment/DD_belatedpng/">Drew Diller</a></p>';
      break;
  }
  return $output;
}

/**
 * Implements hook_init().
 */
function alogo_png_init() {
  $alogo_pngapply = variable_get('alogo_png_selectors', '');
  // Split each line so we can implode them later on
  $alogo_pngapply = preg_split('/[\n|\r|\r\n|,]+/', strip_tags($alogo_pngapply));
  $alogo_pngapply = implode(',', $alogo_pngapply);

  if (!empty($alogo_pngapply)) {
    drupal_set_html_head('<!--[if lt IE 7]>
<script type="text/javascript" src="'. base_path() . drupal_get_path('module', 'alogo_png') . '/DD_belatedPNG_0.0.8a-min.js"></script>
<script type="text/javascript">
  DD_belatedpng.fix("' . $alogo_pngapply . '");
</script>
<![endif]-->');
  }
}

/**
 * Implements hook_menu().
 */
function alogo_png_menu() {
  $items = array();

  $items['admin/settings/alogo_png'] = array(
    'title' => 'Alogo PNG Settings',
    'description' => 'Configure alogo_png.',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('alogo_png_admin'),
    'file' => 'alogo_png.admin.inc',
  );

  return $items;
}